### ISSUE TITLE
Volunteer must not able add donor other then his own hall and unknown.

### ISSUE THREAD

**Issue by Hmasum18** [mirmahathir1/badhan-backup#13]
### Currently, a volunteer can add donors to another hall.   

<img src="https://user-images.githubusercontent.com/55390870/127487005-1191e74a-ca1e-4915-b1eb-5706ae5ca610.png"
width = "50%"
/>

### But a volunteer from a hall for example titumir hall, should only have the option to add donors in titumir hall and unkown.

**Comment by mirmahathir1** [comment]
It's already blocked. Although the dropdown shows all halls, you won't be able to create a donor of a hall you are not a resident of.

**Comment by Hmasum18** [comment]
@MH-rahat bhai. Should we consider the issue as solved?

**Comment by MH-rahat** [comment]
yes it is solved
