### ISSUE TITLE
Donor data should not be visible after deletion. Currently you have to refresh the page to see the changes after deletion.

### ISSUE THREAD

**Issue by Hmasum18** [mirmahathir1/badhan-backup#15]
### Go to a donor's profile and in edit mode delete the donor.
<img src ="https://user-images.githubusercontent.com/55390870/127488779-a780d4b4-1719-4061-9b72-3eca8bd265b4.png"
width="70%"/>

### After successful deletion, you will be redirected to the home page, but deleted donor's data is still visible in the home.  

<img src ="https://user-images.githubusercontent.com/55390870/127488827-84f77312-7880-474b-bbff-ce83ca57711f.png"
width="70%"/> 

### You have to refresh the page to see the changes after deletion which should be done when redirected to the home page.

<img src ="https://user-images.githubusercontent.com/55390870/127488862-da0c15ac-619b-4933-8a6a-d7dd7b698ce5.png"
width="70%"/>

**Comment by mirmahathir1** [comment]
You will now have to click on click to reload after getting back from user profile. @Hmasum18 , @MH-rahat confirm this in test site.
