### ISSUE TITLE
JSON data structure to create new dummy user for testing

### ISSUE THREAD

**Issue by Hmasum18** [mirmahathir1/badhan-backup#17]
It will be helpful for us if you provide us the JSON data structure to create dummy users. It will make the testing process faster.

**Comment by mirmahathir1** [comment]
I have shared a sample json in messenger. Also, I have added suggestion tooltip as follows:
![Screenshot from 2021-08-01 23-49-10](https://user-images.githubusercontent.com/36355905/127780604-ef164a2e-7626-4e38-8a30-1e62abdb29be.png)
