### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by Hmasum18** [mirmahathir1/badhan-backup#29]
# add margin 
![image](https://user-images.githubusercontent.com/55390870/128022327-919e62e8-2486-46d1-b561-188e3cb44936.png)

**Comment by Hmasum18** [comment]
@Sanju-Basak  edit this issue for UI imporvement

**Comment by Sanju-Basak** [comment]
# Add tick to public data when unknown is selected
![image](https://user-images.githubusercontent.com/71792339/128344106-c5137806-8b1b-4c61-a8e7-6ab3563dde5e.png)

**Comment by Sanju-Basak** [comment]
# Time Stamp format should be DD/MM/YYYY in comment and call history
![image](https://user-images.githubusercontent.com/71792339/128344422-f1cf75cd-3c77-4777-8207-01bb7e3175b8.png)
![image](https://user-images.githubusercontent.com/71792339/128344472-a0957938-e125-4342-8f75-acafb746c3fa.png)

**Comment by MH-rahat** [comment]
![Screenshot_2021-08-05-18-26-35-004_com android chrome](https://user-images.githubusercontent.com/38842742/128353499-1cb438d6-71de-468a-a8ca-120578aac620.jpg)
last donation date should be sorted automatically.

**Comment by MH-rahat** [comment]
![Screenshot_2021-08-05-18-59-53-016_com android chrome](https://user-images.githubusercontent.com/38842742/128354035-14766989-ba23-4e55-87e6-54278fd0d1d3.jpg)
delete last called and call now from donor details.Also if possible, create a 3 dots menu in the top right corner,put share and delete option there.

**Comment by MH-rahat** [comment]
after putting share and delete in 3dots menu, put last donation on top,in the place of last called on

**Comment by MH-rahat** [comment]
Select "public data" as default instead of "select hall"

**Comment by MH-rahat** [comment]
![Screenshot_2021-08-05-21-26-48-066_com android chrome](https://user-images.githubusercontent.com/38842742/128379484-4e23256c-6510-4522-9b16-acf2a0a4027c.jpg)
Sort the last donations date,currently it is sorted on input sequence
