### ISSUE TITLE
Add an option to see if any duplicate user exist with the same phone number in donor creation

### ISSUE THREAD

**Issue by Hmasum18** [mirmahathir1/badhan-backup#32]
Maybe a button below the phone number edit text named "check duplicate" may come in handy.

![image](https://user-images.githubusercontent.com/55390870/128487399-e8ed0acc-f98c-44fb-9cb4-04dd5c1c35fe.png)

**Comment by mirmahathir1** [comment]
Added asynchronous duplication check.
