### ISSUE TITLE
Create app summary video for google play store

### ISSUE THREAD

**Issue by mirmahathir1** [mirmahathir1/badhan-backup#82]
Any app has some sort of video to demonstrate all the features of the app. Make one for ours with a gentle music, animations etc like the ss below, upload on youtube and attach the link to the app.
![Screenshot_20211031_234826_com android vending](https://user-images.githubusercontent.com/36355905/139595718-08791603-d743-4614-9d5e-6b1570b4ee48.jpg)

**Comment by MH-rahat** [comment]
Done
https://youtu.be/-8RgBST52kk
